# Generated by Django 3.2 on 2022-04-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_remove_order_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default=False, null=True),
        ),
    ]
