# Generated by Django 3.2 on 2022-04-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='datetime',
        ),
    ]
