# Generated by Django 3.2 on 2022-09-01 08:16

from django.db import migrations
from django.db.models import F

def set_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for order_item in OrderItem.objects.all().iterator():
        order_item.price = order_item.product.price
        order_item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_auto_20220826_0839'),
    ]

    operations = [
        migrations.RunPython(set_price, migrations.RunPython.noop),
    ]
